### ISSUE TITLE
Check for the compatability with new ~700mb update

### ISSUE THREAD

**Issue by maxim-fedotov-1997** [wd357dui/Elements-of-Harmony#4]
So, update happened. At least Assembly-CSharp.dll at a quick glance was changed. I think it wouldn't hurt to check if this mod is still compatible with new version (_and that could also allow me to update guide I'm upkeeping in community hub on Steam_).
https://steamdb.info/app/1600780/history/?changeid=15431032

**Comment by wd357dui** [comment]
everything seems fine on my end at the moment, I have yet to find any incompatibilities (I will leave this issue open until we find any, or until when a week has passed and there still haven't been any)

- the update didn't change `ScriptingAssemblies.json` or `RuntimeInitializeOnLoads.json`, thus no additional work is required if you applied this mod before you update the game

During my test:
- [x] in the audio menu, I can still switch to a custom language and the Russian language (and then switch back) without issue
- [x] in game, custom language's text and audio can still be loaded without issue
